### PR TITLE
Determining ASPath ASN size (2 or 4 bytes)

### PR DESCRIPTION
**Pull request by thepacketgeek**
Hey @DevQps, I've been playing around with bgp-rs to parse BGP messages received in packets and just have a question about the AS_PATH parsing. I have been working on parsing [this pcap](https://www.cloudshark.org/captures/00249be4441f) which has 2 byte ASNs in the AS_PATH attributes.

The changes below work for me ([debug output](https://gist.github.com/thepacketgeek/d7ff94bdce21fe073124fc3ec142a648)), but the tests fail with a weird issue where the segment length is 0?

```
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/ripe-fbd5739283ab296a

running 2 tests
test parse_updates ... FAILED
test parse_rib ... FAILED

failures:

---- parse_updates stdout ----
thread 'parse_updates' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("Unknown AS_PATH segment size found: 0") }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- parse_rib stdout ----
thread 'parse_rib' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("Unknown AS_PATH segment size found: 0") }', src/libcore/result.rs:997:5


failures:
    parse_rib
    parse_updates

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
```

I'm not familiar at all with MRT, so maybe having a segment with 0 size is legit? Thoughts?

A snippet with the code I'm using is [here](https://gist.github.com/thepacketgeek/9339ec221703dd21673af5e37d36cb49).

### CODE REVIEW

**Comment by DevQps** [comment]
@thepacketgeek Thanks for your issue submission! I'll go and look into it right away! I hope to have an answer ready in a few hours (Y)

**Comment by DevQps** [comment]
Alright I took a look at it and if I understand your code correctly I think the problem lies with trying to determine the size of an AS inside an AS_PATH.

Let's take an example to clarify this:
```
1. AS_PATH with one segment of 2 32-bit ASN:
= 10 bytes (2 bytes for the segment header)

According to your code:
let asn_bytes_size = (10 - 2) / 10 = 8 / 10 = 0?
```
So in other words: It computes the asn_bytes_size wrong I guess! (division with integers ignores any fractions that might occur)

__________

EDIT: I removed part of my previous comment, since I made a serious error in my logic:
the length field is the number of elements so we can use that for figuring out the size of the ASN. Give me about one hour to come up with something else :)

**Comment by DevQps** [comment]
Here is the relevant RFC as well!: https://tools.ietf.org/html/rfc6793

**Comment by DevQps** [comment]
@thepacketgeek

I have looking into this and it basically comes down to the fact that you cannot know the size of each ASN in advance. It's because of this:

Each segment states the type of the segment and the size in elements. However, if we have multiple segments we cannot know how long they are. For example:

```
18 bytes worth of segments might be interpreted as:
2 bytes for the header of a segment + 4x 32-bit ASN
or as two segments of which one contains 4 16-bit ASN and one 3 16-bit ASN.
```

So in the end there is no way of knowing this without having the OPEN message in question.

## Solution
I created a new branch called 16-bit-asn-support. I still need to tweak it a bit more. But you should be able to access it for now using:

```
[dependencies]
bgp-rs = { git = "https://github.com/DevQps/bgp-rs/", branch = "16-bit-asn-support" }
```

```
let mut reader = bgp_rs::Reader::new(cursor);
reader.capabilities.FOUR_OCTET_ASN_SUPPORT = false;
```

It then parses everything as 16-bit ASN. I also figured out there was an error in parsing the BGP Open messages and I added the RouteRefresh capability as well. I hope to have polished everything somewhere in the coming days. I will then merge it to the master branch and release it.

Hope that helps!

**Comment by thepacketgeek** [comment]
Thanks for the quick response!! I should have started with this earlier, but I'm new to rust and digging into something that I know (packets) to get a feel for it. It's been a great learning experience looking through this library to get an idea for how the packet parsing is done :)

I agree with your statement that if we have multiple segments, my fix above will not work. This problem does seem to be complex, the [Wireshark parsing here](https://github.com/wireshark/wireshark/blob/3a514caaf1e3b36eb284c3a566d489aba6df5392/epan/dissectors/packet-bgp.c#L5958) is pretty complicated, haha.

### Possible Solution
I do think I have another idea for how to dynamically guess 2 or 4 byte ASNs, even with multiple segments:

If we create an intermediate structure for each possible segment like:
```
struct Segment {
    count: u16,      // Number of ASNs in path
    bytes: Vec<u8>,  // All of the segment bytes (not split into 2/4 byte chunks)
}

let segments: Vec<Segment> = Vec::new();
```

... and build up this vec in the `for _ in 0..length {` loop, we should be able to guess 2 or 4 byte ASNs like so (assuming, which I believe we can from the RFC, that each PathSegment only uses AS2 or AS4:

```
let asn_count = segments.map(|s| s.count).sum();
let asn_length = segments.map(|s| s.bytes.length()).sum(); 
let asn_byte_size = asn_length / asn_count;
```

I appreciate the work you did in the 16-bit-asn-support branch! I think that deriving the ASN length dynamically still be necessary since different peers might be using AS2 or AS4, and a global setting might not be granular enough?

I'll see if I can get something working like my idea above.

**Comment by DevQps** [comment]
@thepacketgeek I just missed your response earlier on! Your comment appears first, so I guess you haven't seen my latest reply by that time right?

Not sure if you agree with my rationale, but I guess it means that a dynamic approach cannot work since it can still be interpreted in multiple ways even if the size among segments stays the same.

When I deleted a huge part of my previous comment, I was thinking about your solution as well, only to figure out that you'd run into other issues maybe...

Did you understand my example in the previous comment btw? (About segment data being able to be interpreted as multiple segments or one?)

EDIT: For some reason the comments here seem out of order...

EDIT 2: About having multiple peers, if one is having a bigger system, it can create a Reader for each peer, even though it is a bit of a hassle having to do that every time though... I wish there was a better solution.

**Comment by thepacketgeek** [comment]
Regarding the out of order comments, Github doesn't seem to handle the different timezones well :)

Also, yeah, I now understand what you're saying about not being able to dynamically determine the ASN size. That makes sense also about the Reader per peer (probably instantiate per incoming packet too), so we can use the byte size capability advertised in the OPEN. :)

Thank you again for the quick replies!

**Comment by DevQps** [comment]
@thepacketgeek Sorry for the late response! I am on vacation right now but I will update and merge the branch as soon as I am home next week. I'll let you know!

**Comment by thepacketgeek** [comment]
Sounds great, I appreciate all your work! The new branch is working well :)

**Comment by DevQps** [comment]
Alright! I am home :) I hope to fix everything today :)

**Comment by DevQps** [comment]
Alright! I created some tests and fixed some issues. The syntax slightly changed (the NLRI field now contains NLRIEncoding struct which contain either Prefixes or Prefixes with additional information (such as Path Identifiers) might those ever occur. I will open a Pull Request and release it as a new version!

**Comment by DevQps** [comment]
Alright! @thepacketgeek You can now update your dependencies to

```
bgp-rs = "1.5.0"
```

I added some extra testing as well! It should work :) If you have any questions let me know!

**Comment by thepacketgeek** [comment]
Wonderful, thank you so much!!

**Pull request closed without merging**
