### PR TITLE
Add Basic Support for parsing some Open Capabilities

### PR DESCRIPTION
**Pull request by TheBlueMatt**

### CODE REVIEW

**Comment by DevQps** [comment]
Just as the other one! Sorry for the late reply! I will check ASAP.

**Comment by DevQps** [comment]
@thepacketgeek I think this is also already in #27

**Comment by thepacketgeek** [comment]
Correct, this functionality is included in #27

**Comment by DevQps** [comment]
Ah thanks for your reply! I will close this one as well then.

**Pull request closed without merging**
