### PR TITLE
Fix some compilation warnings

### PR DESCRIPTION
**Pull request by montag451**

### CODE REVIEW

**Comment by DevQps** [comment]
Thanks for this as well. This one one of the first crates I have ever written, so I see some mistakes here and there. Do you think `impl Read` would be even better?

**Comment by montag451** [comment]
For a first one, it's pretty good! You are right, `impl Read` is even better!

**Comment by DevQps** [comment]
Thanks! In meanwhile I subscribed to the complete repositories and everything. I hope to start working on it this weekend! You'll hear from me :)

**Comment by montag451** [comment]
I'm looking forward to hearing from you

**Comment by montag451** [comment]
I'm cooking another pull request for you

**Comment by DevQps** [comment]
Thanks! I see that there are also other forks that have many commits with improvements. Maybe we could come together on discord one time to see how to approach everything? Only if you want!

**Comment by DevQps** [comment]
@montag451 I have just had a good call with @thepacketgeek
In his fork he already included many improvements a some new features.
We decided that it would be best to merge his fork into this repository and move forward from there.

We also thought that moving to `impl Read` would be better (for performance as well)! So we hope to change that after we merge his PR as well.

Thanks a lot for your hard work at least! You made me aware that my code was a bit outdated at some places! Once we merge that PR, I'll create a new branch and merge the `impl Read` changes that you inspired from here as well.

Thanks!

**Comment by DevQps** [comment]
Hey Montag! I see that #27 already includes the changes you suggested as well, therefore I will close this PR! I also created an issue for the `impl Read` part: #28 

Thanks a lot for your work!

**Pull request closed without merging**
