### PR TITLE
Fuzz

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Fixes a few bugs, includes all my previous PRs (cause I don't remember what other changes I'd made), and adds basic support for some fuzzing using cargo-fuzz.

### CODE REVIEW

**Comment by thepacketgeek** [comment]
This is awesome @TheBlueMatt ! There's a few visibility changes that I've duplicated in my PR (#25 ), I'll gladly rebase and update my PR over this when it's merged

**Comment by DevQps** [comment]
This is great guys! For some reason I never got any notification on this. I will take a look at them maybe this evening or somewhere this weekend! Kudo's! It's really a shame I didn't see this earlier...

I will check my notifications right away.

**Comment by DevQps** [comment]
@thepacketgeek @TheBlueMatt If you want I could also make you co-maintainers of this crate? I have seen thepacketgeek around at different places and the significant contribution that @TheBlueMatt  has made also shows me that you care about the quality of this crate.

**Comment by thepacketgeek** [comment]
Thank you!! Most of the open requests I've merged into a fork:
https://github.com/thepacketgeek/bgp-rs

There are also some re-organizing and breaking changes in there, would be
great to discuss if they're desired for upstream with a new major version?

**Comment by DevQps** [comment]
@thepacketgeek I just saw your repository today! It looks like you already did some major contributions there. I didn't have the time yet to take a good look at what the changes actually are. But maybe we could meet on Discord somewhere this or next week to discuss how we can best approach this? EDIT: @TheBlueMatt You're welcome as well of course!

**Comment by TheBlueMatt** [comment]
Ah, hadn't seen your fork @thepacketgeek . It looks like you didn't end up taking the fuzzer or other changes from here in it? Also, whats the MSRV for your fork (the base and this PR, neatly stay buildable on, eg, debian stable).

**Comment by TheBlueMatt** [comment]
As for helping maintain, sadly, I dont really have the time to take on such a project right now. Also, I don't appear to have nearly the grand ambitions that @thepacketgeek does :p. After this PR my goal of being able to query a live routing table from rust code by peering with a full-tables peer more than worked, so I'm happy.

**Comment by thepacketgeek** [comment]
Ah, I merged some of it in this commit: https://github.com/thepacketgeek/bgp-rs/commit/f7234e5c8ba6b7207fa5b0295a13619d9eadefbe, if some later changes got missed I can add those.

Also @TheBlueMatt , what's MSRV?

**Comment by TheBlueMatt** [comment]
Minimum Supported Rust Version (sorry, don't you just love TLAs?). If you haven't already, you should try to see how far back you can go (hopefully at least 1.34.2, which is the latest in several major distros) and add it to the travis config beside stable and beta.

**Comment by thepacketgeek** [comment]
Ah, that makes sense!

**Comment by DevQps** [comment]
@thepacketgeek @TheBlueMatt About a meeting time: I am not sure whether you live in Europe or somewhere else? Otherwise meeting around 20:00 CEST would maybe be the most doable? (12:00 PST) What about next Wednesday? Sunday 8:00 CEST is also possible (that would be Saturday 20:00 PST)

Let me know if you want / can join and I will share my contact details with you :)

**Comment by thepacketgeek** [comment]
@DevQps 20:00 CEST next Wednesday (April 29) works for me!

**Comment by thepacketgeek** [comment]
@TheBlueMatt , I made [some changes](https://github.com/thepacketgeek/bgp-rs/commit/041a32c8d19a8b7a511ecfd59520ab30b86d5f4a) to make sure my current fork supports 1.34.2 :) 

That fork also brings in some other of your changes like:
- Fuzz tests
- Additional Open Capability parsing
- Encoding of messages

There are still some breaking API changes, so we can chat about that with @DevQps about how to move forward

**Comment by DevQps** [comment]
@thepacketgeek Glad to hear that 20:00 CEST is fine with you! My Discord username is: Vrede#5784, feel free to send an message anytime. I will read through the pull requests and changes before then to hopefully get a good grasp of the gap between the current state and your version.

@TheBlueMatt Feel free to join as well if you want to of course!

**Comment by TheBlueMatt** [comment]
Awesome! I’ll take a look and see if it can peer with my BIRD lg.

I’m happy to see the crate is getting maintenance. I know some folks using it for table dump parsing as well so it’s quite appreciated. I wish I had more time to help out but hopefully I’ll be able to test it in my use-case :).

**Comment by DevQps** [comment]
@montag451 I have just had a good call with @thepacketgeek
In his fork he already included many improvements a some new features, including the changes that you proposed here. We decided that it would be best to merge his fork into this repository and move forward from there.

Thanks a lot for your hard work!

**Comment by DevQps** [comment]
Ahh I see that some functionality was not yet included. @thepacketgeek I am not sure how much trouble it would be to include those commits in your PR as well? Otherwise we can add them after we merge that PR as well!

**Comment by thepacketgeek** [comment]
@DevQps , oh! Which ones did I miss, I can add them to the current PR (#27 )

I just double-checked the commits above and they seem to be covered. One difference is the `fn write()` is changed to `fn encode()`

**Comment by DevQps** [comment]
Sorry! I thought because you wrote this that not everything was merged yet. If it already was that is great!

> 
> 
> Ah, I merged some of it in this commit: [thepacketgeek@f7234e5](https://github.com/thepacketgeek/bgp-rs/commit/f7234e5c8ba6b7207fa5b0295a13619d9eadefbe), if some later changes got missed I can add those.

**Comment by DevQps** [comment]
I will close these PRs now because #27 also includes these changes. Thanks for your work @TheBlueMatt !

**Pull request closed without merging**
